// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt72CJrj2aNoLQbsFeqc-a4y103UjD50A',
    appId: '1:571145264987:web:3b00b6b08d617209e2047e',
    messagingSenderId: '571145264987',
    projectId: 'testproject-4c871',
    authDomain: 'testproject-4c871.firebaseapp.com',
    storageBucket: 'testproject-4c871.firebasestorage.app',
    measurementId: 'G-XC78RNS5BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtmsumD9xnq1-GE9OtFikh3ntOuXt76Vc',
    appId: '1:571145264987:android:5a46ea6d0016ab97e2047e',
    messagingSenderId: '571145264987',
    projectId: 'testproject-4c871',
    storageBucket: 'testproject-4c871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVjAxKfmlJ_XLquf7iR-18eGx9UoXCrC0',
    appId: '1:571145264987:ios:71897b53fbb5e706e2047e',
    messagingSenderId: '571145264987',
    projectId: 'testproject-4c871',
    storageBucket: 'testproject-4c871.firebasestorage.app',
    iosBundleId: 'com.example.kigaliSerivesDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVjAxKfmlJ_XLquf7iR-18eGx9UoXCrC0',
    appId: '1:571145264987:ios:71897b53fbb5e706e2047e',
    messagingSenderId: '571145264987',
    projectId: 'testproject-4c871',
    storageBucket: 'testproject-4c871.firebasestorage.app',
    iosBundleId: 'com.example.kigaliSerivesDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt72CJrj2aNoLQbsFeqc-a4y103UjD50A',
    appId: '1:571145264987:web:8b9c9e80f6237cbde2047e',
    messagingSenderId: '571145264987',
    projectId: 'testproject-4c871',
    authDomain: 'testproject-4c871.firebaseapp.com',
    storageBucket: 'testproject-4c871.firebasestorage.app',
    measurementId: 'G-JB8E9YMYR6',
  );
}
